In [1]:
"""
参考リスト
http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction
-> scikit-learnの公式UserGuideの4.2.3、情報が豊富
"""
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [2]:
# CountVectrizerクラス
vectorizer = CountVectorizer()
print(vectorizer)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)


In [3]:
print(type("saa"))
print(type(12))
print((type([1,2,3])))

<class 'str'>
<class 'int'>
<class 'list'>


In [4]:
# vectorizer.fit_transform
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
]
X = vectorizer.fit_transform(corpus)
print(X)
print(type(X))

  (0, 8)	1
  (0, 3)	1
  (0, 6)	1
  (0, 2)	1
  (0, 1)	1
  (1, 8)	1
  (1, 3)	1
  (1, 6)	1
  (1, 1)	1
  (1, 5)	2
  (2, 6)	1
  (2, 0)	1
  (2, 7)	1
  (2, 4)	1
  (3, 8)	1
  (3, 3)	1
  (3, 6)	1
  (3, 2)	1
  (3, 1)	1
<class 'scipy.sparse.csr.csr_matrix'>


In [5]:
# vectorizer.build_analyzer
analyze = vectorizer.build_analyzer()
print(analyze("This is a text document to analyze.") == (
    ['this', 'is', 'text', 'document', 'to', 'analyze']))

True


In [6]:
# vectorizer.get_feature_names
print(vectorizer.get_feature_names() == (
    ['and', 'document', 'first', 'is', 'one',
     'second', 'the', 'third', 'this']))

print(type(X))
print(type(X.toarray()))
print(X.toarray())

True
<class 'scipy.sparse.csr.csr_matrix'>
<class 'numpy.ndarray'>
[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]


In [7]:
# TfidfTransformer class
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer(smooth_idf=False)
print(transformer)

TfidfTransformer(norm='l2', smooth_idf=False, sublinear_tf=False,
         use_idf=True)


In [8]:
# transformer.fit_transform(tf-idf)
counts = [[3, 0, 1],
          [2, 0, 0],
          [3, 0, 0],
          [4, 0, 0],
          [3, 2, 0],
          [3, 0, 2]]

tfidf = transformer.fit_transform(counts)
print(tfidf)                         

print(tfidf.toarray())

  (0, 2)	0.5732079309279059
  (0, 0)	0.8194099510753754
  (1, 0)	1.0
  (2, 0)	1.0
  (3, 0)	1.0
  (4, 1)	0.8808994832762984
  (4, 0)	0.47330339145578754
  (5, 2)	0.8135516873095774
  (5, 0)	0.5814926070688599
[[0.81940995 0.         0.57320793]
 [1.         0.         0.        ]
 [1.         0.         0.        ]
 [1.         0.         0.        ]
 [0.47330339 0.88089948 0.        ]
 [0.58149261 0.         0.81355169]]


In [9]:
tfidf = transformer.fit_transform(X.toarray())
print(X.toarray())
print(tfidf)

[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]
  (0, 8)	0.43306684852870914
  (0, 6)	0.33631504064053513
  (0, 3)	0.43306684852870914
  (0, 2)	0.5694308628404254
  (0, 1)	0.43306684852870914
  (1, 8)	0.24014568197368427
  (1, 6)	0.1864945448191575
  (1, 5)	0.8900617613631526
  (1, 3)	0.24014568197368427
  (1, 1)	0.24014568197368427
  (2, 7)	0.5611595317509138
  (2, 6)	0.23515939227529373
  (2, 4)	0.5611595317509138
  (2, 0)	0.5611595317509138
  (3, 8)	0.43306684852870914
  (3, 6)	0.33631504064053513
  (3, 3)	0.43306684852870914
  (3, 2)	0.5694308628404254
  (3, 1)	0.43306684852870914
